"""refactor models

Revision ID: 850c79ef8319
Revises: c50f0b3ad286
Create Date: 2024-12-09 01:59:48.563602

"""

from collections.abc import Sequence

import sqlalchemy as sa

# see https://stackoverflow.com/a/69063829 for sqlmodel
import sqlmodel
import sqlmodel.sql.sqltypes  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "850c79ef8319"
down_revision: str | None = "c50f0b3ad286"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_number", table_name="users")
    op.drop_table("users")
    op.alter_column(
        "students", "surname", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students", "surname", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.create_table(
        "users",
        sa.Column("number", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("number", name="users_pkey"),
    )
    op.create_index("ix_users_number", "users", ["number"], unique=False)
    # ### end Alembic commands ###
