"""refactor request

Revision ID: 2f15884ef8c1
Revises: ac5e578d100b
Create Date: 2024-12-12 17:14:26.634047

"""

from collections.abc import Sequence

# see https://stackoverflow.com/a/69063829 for sqlmodel
import sqlmodel
import sqlmodel.sql.sqltypes  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "2f15884ef8c1"
down_revision: str | None = "ac5e578d100b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
