"""add_group_course_and_exam

Revision ID: f097df941a9f
Revises: 0cff61f0c8ff
Create Date: 2024-12-25 19:58:52.656247

"""
from collections.abc import Sequence

import sqlalchemy as sa

# see https://stackoverflow.com/a/69063829 for sqlmodel
import sqlmodel
import sqlmodel.sql.sqltypes  # noqa: F401
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f097df941a9f'
down_revision: str | None = '0cff61f0c8ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('groups', sa.Column('exam_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'exam_date')
    op.drop_column('groups', 'course_name')
    # ### end Alembic commands ###
