"""blocks

Revision ID: d8abe333b20a
Revises: 2f15884ef8c1
Create Date: 2024-12-13 18:22:02.849561

"""
from collections.abc import Sequence

import sqlalchemy as sa

# see https://stackoverflow.com/a/69063829 for sqlmodel
import sqlmodel
import sqlmodel.sql.sqltypes  # noqa: F401
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd8abe333b20a'
down_revision: str | None = '2f15884ef8c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='blocked_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='blocked_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'group_id', name='blocked_pkey')
    )
    # ### end Alembic commands ###
