"""add_group_creation_date

Revision ID: 0cff61f0c8ff
Revises: 900229402c58
Create Date: 2024-12-25 19:04:19.362231

"""
from collections.abc import Sequence

import sqlalchemy as sa

# see https://stackoverflow.com/a/69063829 for sqlmodel
import sqlmodel
import sqlmodel.sql.sqltypes  # noqa: F401
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0cff61f0c8ff'
down_revision: str | None = '900229402c58'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'date')
    # ### end Alembic commands ###
