"""refactor models 2

Revision ID: 61abd54732d3
Revises: 850c79ef8319
Create Date: 2024-12-10 01:01:19.761130

"""

from collections.abc import Sequence

import sqlalchemy as sa

# see https://stackoverflow.com/a/69063829 for sqlmodel
import sqlmodel
import sqlmodel.sql.sqltypes  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61abd54732d3"
down_revision: str | None = "850c79ef8319"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "members_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column("members_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
