# see https://pre-commit.com for more information
# see https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-yaml
        args:
          - --unsafe
      - id: check-toml
      - id: check-ast
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.7.4"
    hooks:
      - id: ruff
        args: [--fix, --config, backend/pyproject.toml]
        exclude: ^frontend/(?!tests/)
      - id: ruff-format
        args: [--config, backend/pyproject.toml]
        exclude: ^frontend/(?!tests/)

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.15.0"
    hooks:
      - id: eslint
        args: [--fix, --config=frontend/eslint.config.js]
        exclude: ^(backend/|scripts/)
        files: \.(js|jsx|ts|tsx|vue)$
        types: [file]
        additional_dependencies:
          - eslint@9.15.0
          - globals@15.12.0
          - "@eslint/js@9.15.0"
          - eslint-plugin-vue@9.31.0
          - typescript-eslint@8.15.0
          - eslint-config-prettier@9.1.0

  - repo: https://github.com/ComPWA/prettier-pre-commit
    rev: "v3.3.3"
    hooks:
      - id: prettier
        args: [--write]
        exclude: ^(backend/|scripts/)

ci:
  autofix_commit_msg: "chore(pre-commit.ci): auto format/fix from pre-commit hooks"
  autoupdate_commit_msg: "chore(pre-commit.ci): pre-commit autoupdate"
