services:
  postgres:
    container_name: postgres
    image: postgres:17-bookworm
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  pgdata:
