services:
  postgres-unigate:
    container_name: postgres-unigate
    image: postgres:17-bookworm
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
    volumes:
      - ./postgres/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    network_mode: host
    restart: unless-stopped

  pgadmin-unigate:
    container_name: pgadmin-unigate
    image: dpage/pgadmin4:8.13
    entrypoint:
      - /custom-entrypoint.sh
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL?Variable not set}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD?Variable not set}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_SERVER_JSON_FILE=/tmp/servers.json
    volumes:
      - ./pgadmin/entrypoint.sh:/custom-entrypoint.sh
      - pgadmin_data:/var/lib/pgadmin:rw
    depends_on:
      postgres-unigate:
        condition: service_healthy
        restart: true
        required: true
    network_mode: host
    restart: unless-stopped

  minio-unigate:
    container_name: minio-unigate
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER?Variable not set}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD?Variable not set}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    network_mode: host
    restart: unless-stopped

  mc-unigate:
    container_name: mc-unigate
    image: minio/mc:RELEASE.2024-11-21T17-21-54Z
    entrypoint: >
      /bin/sh -c "
      mc alias set minio ${MINIO_URL} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb minio/${MINIO_BUCKET} || true;
      mc anonymous set download minio/${MINIO_BUCKET} || true;
      tail -f /dev/null;"
    environment:
      - MINIO_URL$=${MINIO_URL?Variable not set}
      - MINIO_BUCKET=${MINIO_BUCKET?Variable not set}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER?Variable not set}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD?Variable not set}
    depends_on:
      minio-unigate:
        condition: service_healthy
        restart: true
        required: true
    network_mode: host
    restart: unless-stopped

  backend-unigate:
    container_name: backend-unigate
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./backend/pyproject.toml
          action: rebuild
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_HOST=${POSTGRES_HOST?Variable not set}
      - POSTGRES_PORT=5432
      - UNIGATE_DB=${UNIGATE_DB?Variable not set}
      - AUTH_DB=${AUTH_DB?Variable not set}
      - MODE=test
      - JWT_SECRET=${JWT_SECRET?Variable not set}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY?Variable not set}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT?Variable not set}
    volumes:
      - ./backend/unigate:/app/unigate
      - ./backend/alembic_unigate:/app/alembic_unigate
      - ./backend/alembic_auth:/app/alembic_auth
      - ./backend/seeders:/app/seeders
    depends_on:
      postgres-unigate:
        condition: service_healthy
        restart: true
        required: true
    network_mode: host
    restart: unless-stopped

  frontend-unigate:
    container_name: frontend-unigate
    build:
      context: ./frontend
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
    env_file:
      - .env
    environment:
      - NUXT_PUBLIC_BASE_URL=${NUXT_PUBLIC_BASE_URL?Variable not set}
      - NUXT_PUBLIC_MINIO_URL=${NUXT_PUBLIC_MINIO_URL?Variable not set}
    volumes:
      - ./frontend:/app
    network_mode: host
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin_data:
  minio_data:
