services:
  postgres-unigate:
    container_name: postgres-unigate
    image: postgres:17-bookworm
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
    volumes:
      - ./postgres/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin-unigate:
    container_name: pgadmin-unigate
    image: dpage/pgadmin4:8.13
    entrypoint:
      - /custom-entrypoint.sh
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL?Variable not set}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD?Variable not set}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_SERVER_JSON_FILE=/tmp/servers.json
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
    volumes:
      - ./pgadmin/entrypoint.sh:/custom-entrypoint.sh
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres-unigate:
        condition: service_healthy
        restart: true
        required: true
    restart: unless-stopped

  minio-unigate:
    container_name: minio-unigate
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      - MINIO_PORT=${MINIO_PORT?Variable not set}
      - MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT?Variable not set}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER?Variable not set}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD?Variable not set}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  mc-unigate:
    container_name: mc-unigate
    image: minio/mc:RELEASE.2024-11-21T17-21-54Z
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio-unigate:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb minio/${MINIO_BUCKET} || true;
      mc anonymous set download minio/${MINIO_BUCKET} || true;
      tail -f /dev/null;"
    environment:
      - MINIO_BUCKET=${MINIO_BUCKET?Variable not set}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER?Variable not set}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD?Variable not set}
    depends_on:
      minio-unigate:
        condition: service_healthy
        restart: true
        required: true
    restart: unless-stopped

  backend-unigate:
    container_name: backend-unigate
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - BACKEND_PORT=${BACKEND_PORT?Variable not set}
      - POSTGRES_HOST=postgres-unigate
      - POSTGRES_PORT=${POSTGRES_PORT?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - AUTH_DB=${AUTH_DB?Variable not set}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY?Variable not set}
      - JWT_SECRET=${JWT_SECRET?Variable not set}
      - MINIO_ENDPOINT=minio-unigate:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER?Variable not set}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD?Variable not set}
    volumes:
      - ./backend/unigate:/app/unigate
    depends_on:
      postgres-unigate:
        condition: service_healthy
        restart: true
        required: true
    restart: unless-stopped

  frontend-unigate:
    container_name: frontend-unigate
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - BASE_URL=${BASE_URL?Variable not set}
      - MINIO_URL=${MINIO_URL?Variable not set}
    volumes:
      - ./frontend:/app
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin_data:
  minio_data:
